name: Monitor de Precos Diario

on:
  schedule:
    - cron: '0 11 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o codigo
        uses: actions/checkout@v3

      - name: Instalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalando dependencias
        run: npm install

      - name: Rodando o Scraper
        env: # ESSA PARTE É OBRIGATÓRIA
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node scraper.js